language: node_js
node_js:
  - 0.8
before_script: 
  - npm install -g grunt-cli
branches:
  only:
    - master
    - 1.3-stable
notifications:
  irc:
    channels:
      - "irc.freenode.org#jquerymobile-dev"
